services:
  db:
    image: mysql:8.0
    container_name: diary_mysql
    environment:
      MYSQL_DATABASE: diary
      MYSQL_USER: diary_user
      MYSQL_PASSWORD: diary_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: